# Generated by Django 4.2.7 on 2023-12-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_petshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petshop',
            name='petshop',
        ),
        migrations.AddField(
            model_name='reserva',
            name='petshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reserva.petshop'),
        ),
    ]
